# Generated by Django 4.2.7 on 2023-11-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('fecha_nacimiento', models.DateField()),
                ('sala', models.CharField(max_length=15)),
                ('turno', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('situacion_de_revista', models.CharField(max_length=20)),
                ('sala', models.CharField(max_length=20)),
                ('turno', models.CharField(max_length=15)),
            ],
        ),
    ]
